"""initial_schema

Revision ID: 1ec9d55e0b29
Revises: 
Create Date: 2026-07-20 13:18:27.017490

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec9d55e0b29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_session',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_session',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GBP', 'JPY', 'CHF', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='searchsessionstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chatrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_session_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.Enum('RAG_RETRIEVAL', 'WEATHER_FETCH', 'PLACES_FETCH', 'FLIGHTS_FETCH', 'LLM_GENERATION', name='agentstep'), nullable=False),
    sa.Column('input', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['search_session_id'], ['search_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_package',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('BUDGET', 'STANDARD', 'LUXURY', name='travelpackagetier'), nullable=False),
    sa.Column('estimated_cost_min', sa.Float(), nullable=False),
    sa.Column('estimated_cost_max', sa.Float(), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GBP', 'JPY', 'CHF', name='currency'), nullable=False),
    sa.Column('transportation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('travel_tips', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('weather_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['search_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('type', sa.Enum('HOTEL', 'HOSTEL', 'AIRBNB', name='accommodationtype'), nullable=False),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('cost_per_night', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('extra_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['travel_package.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('travel_package_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estimated_daily_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['travel_package_id'], ['travel_package.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('SIGHTSEEING', 'FOOD', 'ADVENTURE', name='activitytype'), nullable=False),
    sa.Column('itinerary_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('average_duration_hours', sa.Integer(), nullable=True),
    sa.Column('part_of_day', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='partofday'), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('itinerary')
    op.drop_table('accommodation')
    op.drop_table('travel_package')
    op.drop_table('search_history')
    op.drop_table('chat_message')
    op.drop_table('search_session')
    op.drop_table('chat_session')
    op.drop_table('user')
    # ### end Alembic commands ###
